[package]
name = "datapet_codegen"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.1"

[lib]
proc-macro = true

[dependencies]
datapet_lang = { path = "../datapet_lang" }
proc-macro2 = "1"
quote = "1"
syn = "1"

