[workspace]
resolver = "2"
members = [
    "datapet",
    "datapet_codegen",
    "datapet_lang",
    "datapet_support",
    "examples/datapet_example_index_first_char",
    "examples/datapet_example_tree",
    "examples/datapet_example_wordlist",
]
