[package]
name = "datapet_support"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"

[dependencies]
derive_more = "0.99"
derive-new = "0.5"
fallible-iterator = "0.2"
lazy_static = "1"
thiserror = "1"

[dev-dependencies]
assert_matches = "1"
